ui: tape
browserify:
  - transform:
      name: babelify
      presets:
        - es2015
        - react
html: test/build.html
browsers:
  - name: chrome
    version: [latest, beta]
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  - name: microsoftedge
    version: latest
